version: '2'
services:
    zookeeper:
        image: zookeeper:3.5
        container_name: zookeeper
        ports:
            - "${HOST_INNER_IP}:2181:2181"
        volumes:
            - ./data/zookeeper/data:/data
            - ./data/zookeeper/datalog:/datalog
    kafka:
        image: wurstmeister/kafka:2.11-2.0.1
        container_name: kafka
        depends_on:
            - "zookeeper"
        ports:
            - "${HOST_IP}:41523:9092"
            # - "${HOST_INNER_IP}:9997:1099"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092
            KAFKA_LISTENERS: INSIDE://:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
            # Broker id
            KAFKA_BROKER_ID: 0
            # 分区数
            KAFKA_NUM_PARTITIONS: 5
            # 读写线程数
            KAFKA_NUM_NETWORK_THREADS: 16
            KAFKA_NUM_IO_THREADS: 32
            # 数据目录
            KAFKA_LOG_DIRS: /data/log_data
            # kafka自身日志目录
            KAFKA_LOG_DIR: /data/logs
            # cleanup策略
            KAFKA_LOG_CLEANER_ENABLE: "true"
            KAFKA_LOG_CLEANUP_POLICY: delete
            # 数据保留
            KAFKA_LOG_RETENTION_HOURS: 72
            # 日志分割
            # 日志滚动的周期时间
            KAFKA_LOG_ROLL_HOURS: 1
            KAFKA_LOG_SEGMENT_BYTES: 1073741824
            KAFKA_LOG_SEGMENT_DELETE_DELAY_MS: 0
            KAFKA_ADVERTISED_HOST_NAME: kafka_default
            # # jmx
            # JMX_PORT: 1099
            # KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
        volumes:
            # data目录
            - ./data/kafka/data:/data/log_data
            # log目录
            - ./data/kafka/logs:/data/logs

        kafka-manager:
            image: hlebalbau/kafka-manager:1.3.3.18
            container_name: kafka-manager
            depends_on:
                - "kafka"
            ports:
                - "${HOST_INNER_IP}:39001:9000"
            environment:
                ZK_HOSTS: "zookeeper:2181"
            command: -Dpidfile.path=/dev/null