version: "3"

services:
  consul:
    image: consul:1.4.4
    ports:
      - 8500:8500
    networks:
      - default
      - micro_net

  rabbitmq:
    image: rabbitmq:3
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default
      - micro_net

  nats:
    image: nats:1.4.1
    ports:
      - 14222:4222
      - 16222:6222
      - 18222:8222
    networks:
      - default
      - micro_net

networks:
  micro_net:
    external: true
