version: "3"

services:
  nginx:
    image: nginx:1.15
    privileged: true
    ports:
      - 80:80
    volumes:
      - /Users/wuyuxin/Documents/dockerdata/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Users/wuyuxin/Documents/dockerdata/nginx/conf.d/:/etc/nginx/conf.d/
      - /Users/wuyuxin/Documents/dockerdata/nginx/log/:/var/log/nginx/
      - /Users/wuyuxin/Documents/dockerdata/www/:/dockerdata/www/
    links:
      - "php7cache"

  php7cache:
    build: .
    privileged: true
    volumes:
      - /Users/wuyuxin/Documents/dockerdata/:/dockerdata/
      - /Users/wuyuxin/Documents/dockerdata/php/etc:/usr/local/php7cache/etc
    tty: true
    networks:
      - default
      - app_net
    external_links:
      - mysql

networks:
  app_net:
    external: true

