# Docker compose to have Zookeeper, Kafka, and Kafka Manager running for development.
# Provided by @chris-zen

version: "3"
services:
  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=172.16.21.143
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 
  
  kafka-manager:
    image: hlebalbau/kafka-manager:latest
    ports:
      - "9090:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
