version: '3'

services:
    jaeger-collector:
      image: jaegertracing/jaeger-collector
      ports:
        - "14269"
        - "14268:14268"
        - "14267"
      restart: on-failure
      environment:
        - SPAN_STORAGE_TYPE=elasticsearch
        - ES_SERVER_URLS=http://elasticsearch:9200
      depends_on:
        - elasticsearch

    jaeger-query:
      image: jaegertracing/jaeger-query
      ports:
        - "16686:16686"
        - "16687"
      environment:
        - SPAN_STORAGE_TYPE=elasticsearch
        - ES_SERVER_URLS=http://elasticsearch:9200
      restart: on-failure
      depends_on:
        - elasticsearch

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
      container_name: elasticsearch
      restart: always
      ports:
        - 9200:9200
        - 9300:9300
      environment:
        discovery.type: single-node
      ulimits:
        memlock:
          soft: -1
          hard: -1

    kibana:
      image: docker.elastic.co/kibana/kibana:6.5.4
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch

    spark-dependencies:
      image: jaegertracing/spark-dependencies
      environment:
        - STORAGE=elasticsearch
        - ES_NODES=http://elasticsearch:9200
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - "28080:8080"
      depends_on:
        - elasticsearch
